import MaxContainer from "../common/maxcontainer";

const CookiesPolicyContent = () => {
  return (
    <section className="py-[12rem] bg-[#EFFFEE] text-[#002E20]">
      <MaxContainer>
        <div className="max-w-[130rem] px-[7rem] sm:px-[2.5rem] mx-auto">
          {/* Policy Title and Effective Date */}
          <h1 className="sub_header_i">COOKIES POLICY</h1>
          <p className="p_i mt-[1rem]">
            Effective Date: June 20, 2025
            <br />
            Last Updated: None
          </p>

          {/* 1. INTRODUCTION Section */}
          <div className="mt-[2.5rem]">
            <h2 className="sub_header_ii">1. INTRODUCTION</h2>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Omo Offa Ni Mi Development Union ("we", "our", or "us") is
              committed to protecting the privacy and data rights of all
              individuals who use our digital platforms. This Cookies Policy
              outlines how we use cookies and similar tracking technologies on
              our website, mobile app, and other digital interfaces
              (collectively referred to as the “Site”) to provide services,
              monitor engagement, and improve user experience.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              As a non-profit humanitarian platform, Omo Offa Ni Mi Development
              Union primarily uses digital tools to collect, process, and manage
              data of beneficiaries enrolled in our programs. These activities
              include but are not limited to: registration, welfare program
              coordination, digital documentation of aid distribution, and
              communication with stakeholders. As part of our data collection
              process, cookies help facilitate these interactions securely and
              efficiently.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              In line with the Nigeria Data Protection Act (NDPA) 2023 and
              global standards such as the General Data Protection Regulation
              (GDPR) and the California Consumer Privacy Act (CCPA), we ensure
              that cookie use is transparent, purposeful, and strictly
              regulated. We do not use cookies to profile beneficiaries in any
              way that contravenes their right to dignity, privacy, or lawful
              processing.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              This policy provides comprehensive information about what cookies
              are, how and why we use them, the categories of cookies we deploy,
              how you can control your cookie preferences, and your legal
              rights. Your continued use of the Site constitutes consent to our
              use of cookies, in accordance with this policy.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              We encourage you to read this policy carefully and revisit it
              regularly, as it may be updated to reflect evolving legal
              requirements or technological innovations in our service delivery.
            </p>
          </div>

          {/* 2. WHAT ARE COOKIES? Section */}
          <div className="mt-[2.5rem]">
            <h2 className="sub_header_ii">2. WHAT ARE COOKIES?</h2>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Cookies are small text files stored on your device (computer,
              tablet, or smartphone) when you visit a website. They are
              generated by a web server and sent to your browser, allowing the
              site to recognise your device and retain information about your
              preferences or past actions.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              These files serve a wide variety of functions. For instance, they
              can remember your login details so that you do not have to
              re-enter them each time you access a secure area. Cookies also
              support faster navigation, enable the delivery of personalised
              content, and help monitor user behaviour for analytical and
              administrative purposes.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Cookies can be classified based on duration and source. Session
              cookies expire when you close your browser, while persistent
              cookies remain on your device for a specified period. First-party
              cookies are placed directly by Omo Offa Ni Mi Development Union,
              while third-party cookies are set by service providers integrated
              into our platform, such as analytics or cloud-hosting services.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Cookies do not typically collect personal data that identifies you
              directly. However, some cookies may interact with information that
              becomes personal when combined with other data (such as a user ID
              or IP address), in which case the protections under the NDPA and
              other applicable privacy laws apply.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              We use cookies responsibly and in accordance with applicable
              legislation, ensuring that the data collected is minimised,
              anonymised when possible, and strictly used for legitimate
              purposes related to service delivery, platform performance, and
              beneficiary engagement.
            </p>

            {/* Duration of Cookies Sub-section (Integrated here) */}
            <div className="mt-[2.5rem]">
              <h3 className="sub_header_ii">Duration of Cookies</h3>
              <p className="mt-[1rem] p_i mb-[1.3rem]">
                Cookies deployed on Omo Offa Ni Mi Development Union platform
                vary in duration depending on their function and classification.
                As a privacy-conscious organisation, we minimise cookie lifespan
                to what is reasonably necessary to fulfil their intended
                purpose.
              </p>
              <p className="mt-[1rem] p_i mb-[1.3rem]">
                Session cookies are temporary cookies that are erased when you
                close your browser. They help maintain session integrity,
                particularly when filling out registration forms or navigating
                secured areas of our Site. These cookies do not store any
                personal data and are essential for a smooth and secure browsing
                experience.
              </p>
              <p className="mt-[1rem] p_i mb-[1.3rem]">
                Persistent cookies, on the other hand, remain stored on your
                device until they expire or are manually deleted. These cookies
                typically remember login credentials (if opted), language
                settings, and other custom preferences. The duration of
                persistent cookies may range from a few days to a maximum of 13
                months, in accordance with NDPA and global best practices.
              </p>
              <p className="mt-[1rem] p_i mb-[1.3rem]">
                Each cookie placed—whether by us or a third-party provider—has a
                predefined expiry date embedded in its configuration. We ensure
                that no cookie remains active beyond its justified lifecycle,
                and we regularly audit cookie lifespans to ensure compliance
                with applicable privacy laws.
              </p>
              <p className="mt-[1rem] p_i mb-[1.3rem]">
                You may at any time clear both session and persistent cookies
                manually through your browser settings. Doing so, however, may
                affect your experience and disable custom features that depend
                on cookies.
              </p>
              <p className="mt-[1rem] p_i mb-[1.3rem]">
                We maintain a cookie inventory and lifecycle policy as part of
                our data retention governance framework and ensure automated
                purging of expired cookies where technically feasible.
              </p>
            </div>
          </div>

          {/* 3. WHY WE USE COOKIES Section */}
          <div className="mt-[2.5rem]">
            <h2 className="sub_header_ii">3. WHY WE USE COOKIES</h2>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              We use cookies for several lawful and specific purposes aimed at
              improving your experience as a user or beneficiary of Omo Offa Ni
              Mi Development Union. First, cookies help ensure that the website
              functions as intended—enabling features such as secure login, form
              submissions, and session management.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Secondly, cookies allow us to analyse how users interact with the
              Site. These performance cookies collect anonymised information
              that helps us understand which pages are most visited, how users
              navigate our platform, and where improvements may be necessary.
              This data enables us to optimise our digital tools for
              accessibility and user-friendliness, especially for low-income
              beneficiaries who may be digitally marginalised.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Thirdly, we use cookies to remember your preferences. For example,
              if you choose a particular language, regional setting, or
              accessibility mode, functionality cookies ensure that your choices
              persist on future visits. This improves user satisfaction and
              reduces the barriers to accessing essential services.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Fourth, in specific instances, we use cookies to personalise
              content, such as displaying custom messages, reminders about
              program schedules, or relevant community updates. These cookies
              are designed to respect your privacy and are never used to display
              third-party advertisements or intrusive marketing.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Finally, cookies help ensure security on our platform. We use
              certain cookies to detect fraudulent activity, ensure
              authentication integrity, and monitor system vulnerabilities. This
              is especially crucial as we handle sensitive welfare data,
              including health, household, and financial conditions of our
              beneficiaries.
            </p>
          </div>

          {/* 4. CATEGORIES OF COOKIES WE USE Section */}
          <div className="mt-[2.5rem]">
            <h2 className="sub_header_ii">4. CATEGORIES OF COOKIES WE USE</h2>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              The cookies we use fall into four main categories, each serving a
              distinct and lawful purpose in line with the NDPA and global
              privacy frameworks. These categories are Strictly Necessary,
              Performance, Functionality, and Analytics Cookies.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              **Strictly Necessary Cookies** are essential for the Site to
              function. They enable core functions like secure login, user
              authentication, session management, and application form
              completion. Without these cookies, parts of our platform would not
              work properly. These cookies do not store any personal data and
              cannot be disabled.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              **Performance Cookies** allow us to gather statistical information
              about how visitors use our Site. These cookies track user
              behaviour anonymously—such as time spent on a page or links
              clicked—and help us identify and fix usability issues. Performance
              cookies enhance our understanding of how users engage with our
              programs online.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              **Functionality Cookies** help us remember your settings and
              choices. For example, if you set the site to display text in a
              larger font for accessibility, this preference is stored via a
              functionality cookie. These cookies are important for inclusivity,
              particularly for visually impaired users or those with limited
              digital literacy.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              **Analytics Cookies**, often placed by third-party providers like
              Google Analytics, help us track overall website traffic and
              demographics. The data from these cookies is used in aggregate
              form and never identifies individual users. It assists us in
              planning digital campaigns and improving service delivery
              outcomes.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              We do not currently use advertising cookies, and we do not allow
              third-party marketing on our Site. Should this policy change, we
              will seek your explicit consent before deploying any such cookies.
            </p>
          </div>

          {/* 5. CONSENT AND LEGAL BASIS Section */}
          <div className="mt-[2.5rem]">
            <h2 className="sub_header_ii">5. CONSENT AND LEGAL BASIS</h2>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              In compliance with the Nigeria Data Protection Act 2023, cookies
              that are not strictly necessary are only activated after we obtain
              your informed, freely given, specific, and unambiguous consent.
              Consent is gathered through a pop-up banner when you first visit
              our Site, where you can choose to accept, reject, or customise
              cookie settings.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              This process is transparent and allows you to make granular
              decisions about which categories of cookies you allow. You may
              update your preferences or withdraw consent at any time by
              clicking the "Cookie Settings" link available on the Site footer.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Our legal basis for processing strictly necessary cookies is our
              legitimate interest in ensuring the proper functioning of our
              digital platform. For all other cookies, we rely on your consent,
              as required by the NDPA, GDPR, and similar privacy frameworks.
              This ensures compliance and respects your data sovereignty.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              We record and store your consent status in a secure database to
              demonstrate compliance with regulatory obligations. We may also
              use a third-party tool to manage consent logs in an auditable
              format.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              If you are under the age of 18, or a vulnerable person under the
              care of a guardian, we do not knowingly collect cookies-based data
              unless the guardian consents on your behalf. We encourage parents
              or guardians to contact us for more information on child-friendly
              data policies.
            </p>
          </div>

          {/* 6. THIRD-PARTY COOKIES AND DATA SHARING Section */}
          <div className="mt-[2.5rem]">
            <h2 className="sub_header_ii">
              6. THIRD-PARTY COOKIES AND DATA SHARING
            </h2>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              In some cases, we integrate third-party tools into our Site to
              enhance its usability or collect aggregate usage data. These tools
              may place cookies on your device, and their policies apply in
              addition to ours.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              We carefully vet all third-party service providers to ensure they
              uphold equivalent data protection standards. We have signed Data
              Processing Agreements (DPAs) with these providers, and where
              applicable, we ensure adequate safeguards are in place for
              international data transfers under the NDPA and global standards.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              We do not permit third parties to use cookies for profiling or
              targeting ads to our beneficiaries. Any cookies used by third
              parties on our Site are for performance, security, or
              session-based functionalities only.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              If you click on a link to a third-party site (e.g., a payment
              gateway or partner NGO), their own cookie policies will apply. We
              encourage you to read those policies independently.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Omo Offa Ni Mi Development Union assumes no responsibility for
              cookies used outside of our domain and advises users to exercise
              caution when leaving our Site.
            </p>

            {/* Third-Party Cookies and Tools Sub-section (Integrated here) */}
            <div className="mt-[2.5rem]">
              <h3 className="sub_header_ii">Third-Party Cookies and Tools</h3>
              <p className="mt-[1rem] p_i mb-[1.3rem]">
                To enhance the functionality and analytics of our Site, Omo Offa
                Ni Mi Development Union incorporates cookies and tracking tools
                from trusted third-party service providers. These third parties
                set cookies on our Site to collect non-personally identifiable
                information for legitimate purposes, including performance
                tracking, security analytics, and user experience improvement.
              </p>
              <p className="mt-[1rem] p_i mb-[1.3rem]">
                One such tool is Google Analytics, which helps us understand how
                users interact with our platform by tracking page visits, bounce
                rates, and general user behaviour. This data is collected in
                aggregated form and is used solely to enhance content delivery,
                navigation, and accessibility. IP addresses are anonymised
                before storage to ensure compliance with data protection
                regulations.
              </p>
              <p className="mt-[1rem] p_i mb-[1.3rem]">
                We may also use the Meta Pixel (formerly Facebook Pixel) to
                measure the effectiveness of community engagement campaigns or
                track conversions related to awareness drives or fundraising
                efforts. This data is not used for commercial advertising or
                profiling but helps us improve communication with our audience.
              </p>
              <p className="mt-[1rem] p_i mb-[1.3rem]">
                All third-party cookies used on our platform are subject to
                their respective privacy policies, which we encourage you to
                review. You can find these at:
              </p>
              <ul className="list-disc pl-4 flex list-inside flex-col gap-[.5rem]">
                <li className="p_i">
                  Google Privacy Policy:{" "}
                  <a
                    href="https://policies.google.com/privacy"
                    className="text-blue-600 hover:underline"
                  >
                    https://policies.google.com/privacy
                  </a>
                </li>
                <li className="p_i">
                  Meta (Facebook) Privacy Policy:{" "}
                  <a
                    href="https://www.facebook.com/policy.php"
                    className="text-blue-600 hover:underline"
                  >
                    https://www.facebook.com/policy.php
                  </a>
                </li>
                <li className="p_i">
                  Cloudflare Privacy Policy (if used):{" "}
                  <a
                    href="https://www.cloudflare.com/privacypolicy/"
                    className="text-blue-600 hover:underline"
                  >
                    https://www.cloudflare.com/privacypolicy/
                  </a>
                </li>
              </ul>
              <p className="mt-[1rem] p_i mb-[1.3rem]">
                We carefully vet each third-party vendor for data protection
                compliance and ensure that Data Processing Agreements (DPAs) are
                in place before any integration. Where applicable, we ensure
                international data transfers are subject to appropriate
                safeguards in line with the NDPA and other applicable laws.
              </p>
              <p className="mt-[1rem] p_i mb-[1.3rem]">
                Users are advised to read the linked policies to fully
                understand how their information may be handled by these
                third-party platforms. We accept no liability for third-party
                cookies used outside the scope of our direct service operations.
              </p>
            </div>
          </div>

          {/* 7. MANAGING YOUR COOKIE PREFERENCES Section */}
          <div className="mt-[2.5rem]">
            <h2 className="sub_header_ii">
              7. MANAGING YOUR COOKIE PREFERENCES
            </h2>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              You have full control over how cookies are used on your device. At
              any time, you can manage or disable cookies by adjusting the
              settings in your browser. Most modern browsers allow you to block
              cookies, delete existing cookies, or set preferences for certain
              websites.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Instructions for managing cookies can be found on browser support
              pages:
            </p>
            <ul className="list-disc pl-4 flex list-inside flex-col gap-[.5rem]">
              <li className="p_i">
                Google Chrome:{" "}
                <a
                  href="https://support.google.com/chrome/answer/95647"
                  className="text-blue-600 hover:underline"
                >
                  https://support.google.com/chrome/answer/95647
                </a>
              </li>
              <li className="p_i">
                Mozilla Firefox:{" "}
                <a
                  href="https://support.mozilla.org/en-US/kb/cookies-information-websites-store-on-your-computer"
                  className="text-blue-600 hover:underline"
                >
                  https://support.mozilla.org/en-US/kb/cookies-information-websites-store-on-your-computer
                </a>
              </li>
              <li className="p_i">
                Safari:{" "}
                <a
                  href="https://support.apple.com/en-us/HT201265"
                  className="text-blue-600 hover:underline"
                >
                  https://support.apple.com/en-us/HT201265
                </a>
              </li>
              <li className="p_i">
                Microsoft Edge:{" "}
                <a
                  href="https://support.microsoft.com/en-us/help/4027947"
                  className="text-blue-600 hover:underline"
                >
                  https://support.microsoft.com/en-us/help/4027947
                </a>
              </li>
            </ul>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Please note that disabling some cookies, particularly the strictly
              necessary ones, may affect the performance and functionality of
              our Site. For example, registration forms or secure login pages
              may no longer function correctly.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              In addition to browser controls, we provide an in-site cookie
              management panel. This tool allows you to revisit your choices and
              toggle different categories of cookies on or off.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              For further help, you can contact our Data Protection Officer via
              the contact details provided below.
            </p>
          </div>

          {/* 8. YOUR RIGHTS Section */}
          <div className="mt-[2.5rem]">
            <h2 className="sub_header_ii">8. YOUR RIGHTS</h2>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              As a user or beneficiary, you have the right to exercise control
              over your personal data, including data collected via cookies.
              These rights are provided under the Nigeria Data Protection Act
              2023 and, where applicable, the GDPR.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">You have the right to:</p>
            <ol className="list-decimal pl-4 flex list-inside flex-col gap-[.5rem]">
              <li className="p_i">
                Request access to personal data processed via cookies;
              </li>
              <li className="p_i">
                Request the rectification or deletion of such data;
              </li>
              <li className="p_i">Withdraw your consent at any time;</li>
              <li className="p_i">
                Object to processing where cookies are not essential to service
                delivery;
              </li>
              <li className="p_i">
                Lodge a complaint with the Nigeria Data Protection Commission
                (NDPC).
              </li>
            </ol>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Omo Offa Ni Mi Development Union is committed to respecting your
              rights and will act on any request within the statutory timeframe,
              usually within 30 days. We have internal procedures and a
              designated DPO to manage these requests efficiently.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              If your data has been collected by a third party through embedded
              cookies, we will refer you to that third party for further action.
              However, we are available to provide guidance in navigating such
              complaints.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Your privacy and dignity are central to our mission, and we view
              cookie transparency as part of our broader duty of care to
              vulnerable populations.
            </p>
          </div>

          {/* 9. UPDATES TO THIS POLICY Section */}
          <div className="mt-[2.5rem]">
            <h2 className="sub_header_ii">9. UPDATES TO THIS POLICY</h2>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              We may revise this Cookies Policy from time to time to reflect
              changes in legal requirements, technological developments, or our
              internal data governance practices. When we do, we will update the
              "Last Updated" date at the top of this page.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Substantive changes to the way we use cookies will be communicated
              prominently through a notice on our homepage or via email, where
              applicable. We may also prompt you to review or renew your cookie
              consent if the changes significantly alter how your data is
              collected.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              We encourage all users to periodically review this Policy to stay
              informed of our data practices. Continued use of the Site after
              changes implies acceptance of the updated terms.
            </p>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              Archived versions of the Cookies Policy may be made available upon
              request to demonstrate compliance with the NDPA or regulatory
              inquiries.
            </p>
          </div>

          {/* 10. CONTACT US Section */}
          <div className="mt-[2.5rem]">
            <h2 className="sub_header_ii">10. CONTACT US</h2>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              If you have any questions, concerns, or requests related to this
              Cookies Policy or your rights under data protection laws, please
              contact us at:
            </p>
            <ul className="list-disc pl-4 flex list-inside flex-col gap-[.5rem]">
              <li className="p_i">Data Protection Officer</li>
              <li className="p_i">
                Name of Data Controller: Omo Offa Ni Mi Development Union
              </li>
              <li className="p_i">
                Address: No. 3, Opposite Praise Assembly, Church off Olufemi
                Durosaro Avenue, Tanke Oke-Odo, Ilorin, Kwara State, Nigeria.
              </li>
              <li className="p_i">
                Email:{" "}
                <a
                  href="mailto:info@omooffanimi.com"
                  className="text-blue-600 hover:underline"
                >
                  info@omooffanimi.com
                </a>
              </li>
              <li className="p_i">Phone: +2348085085918 or +2348136686235</li>
              <li className="p_i">
                Website:{" "}
                <a
                  href="https://www.omooffanimi.com"
                  className="text-blue-600 hover:underline"
                >
                  www.omooffanimi.com
                </a>
              </li>
              <li className="p_i">
                Data Protection Officer (DPO): Muhammad Naseer Abdullahi, Esq.
              </li>
              <li className="p_i">
                DPO Email:{" "}
                <a
                  href="mailto:dpo@omooffanimi.com"
                  className="text-blue-600 hover:underline"
                >
                  dpo@omooffanimi.com
                </a>
              </li>
            </ul>
            <p className="mt-[1rem] p_i mb-[1.3rem]">
              We are committed to prompt and respectful engagement with all
              inquiries, especially those concerning data rights and
              privacy-related feedback.
            </p>
          </div>
        </div>
      </MaxContainer>
    </section>
  );
};

export default CookiesPolicyContent;
