export const popularProfessions = [
  "Doctor",
  "Nurse",
  "Pharmacist",
  "Civil Engineer",
  "Software Engineer",
  "Mechanical Engineer",
  "Web Developer",
  "Data Analyst",
  "Cybersecurity Expert",
  "Lawyer",
  "Judge",
  "Legal Consultant",
  "Accountant",
  "Banker",
  "Investment Analyst",
  "Entrepreneur",
  "Business Owner",
  "Startup Founder",
  "Teacher",
  "Lecturer",
  "Tutor",
  "Musician",
  "Actor",
  "Content Creator",
  "Petroleum Engineer",
  "Geologist",
  "Farmer",
  "Agribusiness Expert",
  "Architect",
  "Property Developer",
  "Truck Driver",
  "Logistics Manager",
  "Journalist",
  "Copywriter",
  "Tailor",
  "Fashion Designer",
  "Footballer",
  "Coach",
  "Sports Analyst",
  "Student",
  "Others",
];
