export const wards = ["Asalofa", "Balogun", "Essa", "Ojomu", "Shawo"];

export const compounds = [
  "Aade",
  "Aakosin",
  "Aala",
  "Aare-Obadoke-Oja",
  "Aare-Onilu",
  "Aare-Onilu Iya-Oba",
  "Abesingogan",
  "Abiye",
  "Aborisa",
  "Abubiesu",
  "Abugba",
  "Adakerin",
  "Adeere",
  "Adesina",
  "Adifa",
  "Adikuku",
  "Ado",
  "Afimo",
  "Afobara",
  "Agbe",
  "Agbeja",
  "Agbojulogun",
  "Agbolese",
  "Agbontu",
  "Agbopa",
  "Ago",
  "Aiku",
  "Ajele",
  "Ajia Bangbaiye",
  "Ajia-Abudu",
  "Ajibogun",
  "Ajilo",
  "Ajimaasin",
  "Ajibeku",
  "Ajoda",
  "Ajoloju Orun",
  "Akanran",
  "Akeje",
  "Akeke",
  "Akinlofi",
  "Aknisola",
  "Akorede",
  "Akosomu",
  "Alaba",
  "Alagbede",
  "Alagure-Isale",
  "Alagure-Ita-Erin",
  "Alape-Ode",
  "Alaro",
  "Alawe",
  "Alawode",
  "Alowolodu",
  "Alubata Oju-Irin",
  "Alubata Oke-Oro",
  "Aludundu",
  "Amako",
  "Amukude",
  "Amunilodo",
  "Anadoo",
  "Anuode",
  "Aponbi",
  "Apuruntu",
  "Araba",
  "Aranmokola",
  "Ariyunkeyawo",
  "Aro",
  "Arofa",
  "Arogede",
  "Arogun",
  "Arole",
  "Aromasodu",
  "Arowo-Jobe",
  "Arowo-Obe",
  "Asaba",
  "Asalofa",
  "Asanlu",
  "Asaoye",
  "Aselegbe",
  "Atagisoro",
  "Atalaka",
  "Awopa",
  "Awudere",
  "Ayansola",
  "Baale-Agbe",
  "Baale-Ijewu",
  "Baba-Isale",
  "Bakoko",
  "Bale-Gogo",
  "Balogun Oja",
  "Balogun Lawoyin",
  "Balogun-Okoju",
  "Bata-ara",
  "Beleore",
  "Beribepo",
  "Bolude",
  "Bugba",
  "Disi-sango",
  "Dundu",
  "Eesa",
  "Eesa-Oyan",
  "Eesinkin",
  "Eeso-Isale",
  "Eeso-Oke",
  "Ejisun",
  "Esunja Jagun Idi-Isin",
  "Esunja-Jagun-Oloye",
  "Elebolo",
  "Eleerin",
  "Elemona",
  "Elemana-Oke-Oro",
  "Elemoso",
  "Elemoso-Baakasa",
  "Epo",
  "Enla",
  "Esho Pataki",
  "Gbagba",
  "Gbanifa",
  "Gbena Jungudu",
  "Gbena-Ojeke",
  "Idi-Ose",
  "Igba",
  "Ijewu",
  "Ikolaba",
  "Ipe",
  "Isaoye",
  "Iya-Oba",
  "Iyeemi",
  "Jaisa",
  "Jamoodo",
  "Jebe-Obanimomo",
  "Kende",
  "Kolawolu",
  "Kundi",
  "Kure",
  "Ladodo",
  "Lalemi",
  "Lanlu Bashorun",
  "Lasogan",
  "Lemomu",
  "Majedun-Eleegun",
  "Mogaji-Aba",
  "Morija",
  "Obada-Arinfa",
  "Obada-Booye",
  "Obadoke",
  "Obatiwajoye",
  "Odofa",
  "Odiwo",
  "Ofe-Aran",
  "Ogaala",
  "Ogaala-Omo-Oba",
  "Oganaran",
  "Oganla-Laminisa",
  "Ojehun-Ogun",
  "Ojomu Arojo",
  "Ojomu Gedegbe",
  "Ojomu Doyin",
  "Ojude",
  "Okiki-Oke",
  "Ola-Isale",
  "Ola-Oke",
  "Oloe",
  "Ologiri",
  "Olokuku",
  "Ololufon",
  "Olomi",
  "Olomu",
  "Oloola",
  "Olooga",
  "Oriosajo",
  "Olose-Isale",
  "Olowa",
  "Oloya Banleku",
  "Oloya-Arikolobo",
  "Oloya Ori-Okuta",
  "Oluawo Omolaran",
  "Oluawo Alawe",
  "Olugbense",
  "Oluburo",
  "Olukose",
  "Oluode-Elewe",
  "Oluode-Idi-Ogun",
  "Oluoko",
  "Oluokun",
  "Oluolo",
  "Oluoro",
  "Oluoti",
  "Olusin",
  "Oluwe",
  "Oluwonran",
  "Omilola",
  "Onibode",
  "Onigba",
  "Onigosun",
  "Oniju",
  "Onilu-Oke-Igbo",
  "Onipede",
  "Onira",
  "Onise",
  "Onitola",
  "Onto",
  "Ope-Ori",
  "Opepe",
  "Opere",
  "Origi",
  "Osese-lehin",
  "Osun-Ore-O-je",
  "Osunlakun",
  "Osunte",
  "Oyafolu",
  "Oyanisunwa",
  "Oye-Balogun",
  "Oyelehin",
  "Rotimi Dada",
  "Saawo Akubiado",
  "Saawo Aroworale",
  "Saawo Olarewaju",
  "Saba",
  "Safiro",
  "Sakosi",
  "Sala",
  "Sasalabata",
  "Seegi",
  "Sobaloju",
  "Sokosoko",
  "Sule",
  "Tabioloko",
  "Temileke",
  "Yemaja",
];
